blank_issues_enabled: true
contact_links:
  - name: Puii Support
    url: https://t.me/puiisupport
    about: Please drop your doubts or queries there for an immediate response.
  - name: Documentation
    url: https://aelly.tk
    about: Basic documentation for setting up.
